# <span style="color:orange">Transformación y limpieza de datos<span>

In [87]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [88]:
# Algunas funciones que utilizaremos en este archivo
def sep():
    print('---------------------------------------')

def revisar_duplicados(df, col):
    sep()
    dup = df[col].duplicated().sum()
    print(f'Los valores duplicados en la columna {col} es de {dup}')

## <span style="color:orange">---------  Archivo *df_loads_trips.csv*  ---------<span>

In [89]:
# Carga de archivos en bruto
df_loads = pd.read_csv("../datos_en_bruto/loads.csv", sep = ',')
df_trips = pd.read_csv("../datos_en_bruto/trips.csv", sep = ',')

In [90]:
print(f'El número de filas que tenemos en df_loads es {df_loads.shape[0]}, y el número de columnas es {df_loads.shape[1]}')
sep()
print (f'El número de filas que tenemos en df_trips es {df_trips.shape[0]}, y el número de columnas es {df_trips.shape[1]}')

# Nombre de las columnas de ambos archivos
sep()
print('df_loads:\n', df_loads.columns)
sep()
print('df_trips:\n', df_trips.columns)

El número de filas que tenemos en df_loads es 85410, y el número de columnas es 12
---------------------------------------
El número de filas que tenemos en df_trips es 85410, y el número de columnas es 12
---------------------------------------
df_loads:
 Index(['load_id', 'customer_id', 'route_id', 'load_date', 'load_type',
       'weight_lbs', 'pieces', 'revenue', 'fuel_surcharge',
       'accessorial_charges', 'load_status', 'booking_type'],
      dtype='object')
---------------------------------------
df_trips:
 Index(['trip_id', 'load_id', 'driver_id', 'truck_id', 'trailer_id',
       'dispatch_date', 'actual_distance_miles', 'actual_duration_hours',
       'fuel_gallons_used', 'average_mpg', 'idle_time_hours', 'trip_status'],
      dtype='object')

In [91]:
# df_trips['load_id'].head()
# df_trips['load_id'].tail()
# df_loads['load_id'].head()
df_loads['load_id'].tail()

85405    LOAD00085406
85406    LOAD00085407
85407    LOAD00085408
85408    LOAD00085409
85409    LOAD00085410
Name: load_id, dtype: object

<span style="color:orange">En una primera revisión, podemos comprobar que en el archivo trips, el **trip_id** y el **load_id** se corresponden uno a uno, así que vamos a hacer un merge de los dos archivos y trabajar solo con uno pero con más datos<span>

In [92]:
df = df_loads.merge(df_trips, on='load_id', how='inner')
df.shape
print (f'El número de filas que tenemos es {df.shape[0]}, y el número de columnas es {df.shape[1]}')

El número de filas que tenemos es 85410, y el número de columnas es 23

In [93]:
df.describe().round(2).T

,count,mean,std,min,25%,50%,75%,max
weight_lbs,85410.0,27477.50,10095.42,10000.00,18724.00,27482.00,36190.00,45000.00
pieces,85410.0,14.47,8.07,1.00,7.00,14.00,21.00,28.00
revenue,85410.0,3073.71,1883.13,125.93,1443.22,2827.98,4323.16,8125.22
fuel_surcharge,85410.0,350.97,218.03,13.80,161.53,314.64,499.18,891.82
accessorial_charges,85410.0,71.64,70.02,0.00,0.00,50.00,100.00,200.00
actual_distance_miles,85410.0,1430.27,801.93,90.00,717.00,1297.50,2147.00,3391.00
actual_duration_hours,85410.0,25.01,14.19,1.40,12.60,23.00,36.90,67.80
fuel_gallons_used,85410.0,221.83,126.56,12.00,111.80,204.50,326.40,611.90
average_mpg,85410.0,6.50,0.58,5.50,6.00,6.50,7.00,7.50
idle_time_hours,85410.0,7.01,2.88,2.00,4.50,7.00,9.50,12.00

Aquí podemos echar un vistazo a las métricas más importantes

<span style="color:orange">Revisamos los tipos de datos y echamos un primer vistazo a los nulos<span>

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   load_id                85410 non-null  object
 1   customer_id            85410 non-null  object
 2   route_id               85410 non-null  object
 3   load_date              85410 non-null  object
 4   load_type              85410 non-null  object
 5   weight_lbs             85410 non-null  int64
 6   pieces                 85410 non-null  int64
 7   revenue                85410 non-null  float64
 8   fuel_surcharge         85410 non-null  float64
 9   accessorial_charges    85410 non-null  int64
 10  load_status            85410 non-null  object
 11  booking_type           85410 non-null  object
 12  trip_id                85410 non-null  object
 13  driver_id              83696 non-null  object
 14  truck_id               83738 non-null  object
 15  trailer_id             83730 non-null  object
 16  dispatch_date          85410 non-null  object
 17  actual_distance_miles  85410 non-null  int64
 18  actual_duration_hours  85410 non-null  float64
 19  fuel_gallons_used      85410 non-null  float64
 20  average_mpg            85410 non-null  float64
 21  idle_time_hours        85410 non-null  float64
 22  trip_status            85410 non-null  object
dtypes: float64(6), int64(4), object(13)
memory usage: 15.0+ MB

<span style="color:orange">**Revisión de:** <br>
    - nombres de las columnas <br>
    - datos únicos en las cada columna <br>
    - duplicados en load_id y trip_id
<span>

In [95]:
print(df.columns)

for col in df.columns:
    sep()
    print(f'Columna: *** {col} ***:')
    print(df[col].unique())
    
revisar_duplicados(df, 'load_id')
revisar_duplicados(df, 'trip_id')

Index(['load_id', 'customer_id', 'route_id', 'load_date', 'load_type',
       'weight_lbs', 'pieces', 'revenue', 'fuel_surcharge',
       'accessorial_charges', 'load_status', 'booking_type', 'trip_id',
       'driver_id', 'truck_id', 'trailer_id', 'dispatch_date',
       'actual_distance_miles', 'actual_duration_hours', 'fuel_gallons_used',
       'average_mpg', 'idle_time_hours', 'trip_status'],
      dtype='object')
---------------------------------------
Columna: *** load_id ***:
['LOAD00000001' 'LOAD00000002' 'LOAD00000003' ... 'LOAD00085408'
 'LOAD00085409' 'LOAD00085410']
---------------------------------------
Columna: *** customer_id ***:
['CUST00183' 'CUST00076' 'CUST00027' 'CUST00088' 'CUST00185' 'CUST00193'
 'CUST00169' 'CUST00049' 'CUST00075' 'CUST00079' 'CUST00127' 'CUST00052'
 'CUST00168' 'CUST00089' 'CUST00032' 'CUST00022' 'CUST00093' 'CUST00092'
 'CUST00029' 'CUST00047' 'CUST00018' 'CUST00007' 'CUST00041' 'CUST00036'
 'CUST00033' 'CUST00065' 'CUST00073' 'CUST00055' 'CUST00136' 'CUST00135'
 'CUST00016' 'CUST00081' 'CUST00102' 'CUST00119' 'CUST00044' 'CUST00114'
 'CUST00017' 'CUST00190' 'CUST00060' 'CUST00038' 'CUST00109' 'CUST00003'
 'CUST00137' 'CUST00039' 'CUST00101' 'CUST00030' 'CUST00115' 'CUST00181'
 'CUST00156' 'CUST00028' 'CUST00071' 'CUST00170' 'CUST00070' 'CUST00084'
 'CUST00095' 'CUST00091' 'CUST00166' 'CUST00139' 'CUST00177' 'CUST00105'
 'CUST00164' 'CUST00175' 'CUST00116' 'CUST00061' 'CUST00078' 'CUST00045'
 'CUST00194' 'CUST00012' 'CUST00113' 'CUST00121' 'CUST00035' 'CUST00182'
 'CUST00063' 'CUST00165' 'CUST00152' 'CUST00107' 'CUST00171' 'CUST00034'
 'CUST00015' 'CUST00042' 'CUST00198' 'CUST00145' 'CUST00085' 'CUST00040'
 'CUST00094' 'CUST00138' 'CUST00026' 'CUST00126' 'CUST00143' 'CUST00098'
 'CUST00178' 'CUST00117' 'CUST00123' 'CUST00008' 'CUST00192' 'CUST00118'
 'CUST00133' 'CUST00059' 'CUST00010' 'CUST00180' 'CUST00191' 'CUST00125'
 'CUST00159' 'CUST00096' 'CUST00072' 'CUST00009' 'CUST00111' 'CUST00154'
 'CUST00188' 'CUST00174' 'CUST00099' 'CUST00014' 'CUST00080' 'CUST00077'
 'CUST00050' 'CUST00083' 'CUST00074' 'CUST00005' 'CUST00161' 'CUST00025'
 'CUST00031' 'CUST00057' 'CUST00013' 'CUST00200' 'CUST00054' 'CUST00020'
 'CUST00051' 'CUST00086' 'CUST00184' 'CUST00011' 'CUST00167' 'CUST00064'
 'CUST00155' 'CUST00069' 'CUST00199' 'CUST00043' 'CUST00146' 'CUST00176'
 'CUST00162' 'CUST00056' 'CUST00110' 'CUST00058' 'CUST00196' 'CUST00187'
 'CUST00141' 'CUST00163' 'CUST00128' 'CUST00186' 'CUST00147' 'CUST00062'
 'CUST00066' 'CUST00122' 'CUST00021' 'CUST00195' 'CUST00048' 'CUST00037'
 'CUST00046' 'CUST00097' 'CUST00067' 'CUST00149' 'CUST00023' 'CUST00151'
 'CUST00019' 'CUST00053' 'CUST00132' 'CUST00106' 'CUST00173' 'CUST00140'
 'CUST00103' 'CUST00131' 'CUST00120' 'CUST00144' 'CUST00179' 'CUST00090'
 'CUST00006' 'CUST00150' 'CUST00157' 'CUST00100' 'CUST00024' 'CUST00112'
 'CUST00002' 'CUST00104' 'CUST00158' 'CUST00082' 'CUST00129' 'CUST00130'
 'CUST00172' 'CUST00189' 'CUST00197' 'CUST00124' 'CUST00087' 'CUST00108'
 'CUST00004' 'CUST00068' 'CUST00160' 'CUST00153' 'CUST00134' 'CUST00148'
 'CUST00001' 'CUST00142']
---------------------------------------
Columna: *** route_id ***:
['RTE00019' 'RTE00058' 'RTE00048' 'RTE00013' 'RTE00020' 'RTE00004'
 'RTE00038' 'RTE00016' 'RTE00025' 'RTE00052' 'RTE00002' 'RTE00032'
 'RTE00006' 'RTE00015' 'RTE00054' 'RTE00012' 'RTE00001' 'RTE00042'
 'RTE00009' 'RTE00035' 'RTE00034' 'RTE00022' 'RTE00026' 'RTE00010'
 'RTE00033' 'RTE00055' 'RTE00007' 'RTE00056' 'RTE00031' 'RTE00053'
 'RTE00041' 'RTE00036' 'RTE00043' 'RTE00045' 'RTE00051' 'RTE00008'
 'RTE00030' 'RTE00039' 'RTE00046' 'RTE00023' 'RTE00037' 'RTE00028'
 'RTE00050' 'RTE00047' 'RTE00005' 'RTE00024' 'RTE00021' 'RTE00018'
 'RTE00044' 'RTE00014' 'RTE00029' 'RTE00017' 'RTE00003' 'RTE00049'
 'RTE00040' 'RTE00011' 'RTE00057' 'RTE00027']
---------------------------------------
Columna: *** load_date ***:
['2022-01-01' '2022-01-02' '2022-01-03' ... '2024-12-29' '2024-12-30'
 '2024-12-31']
---------------------------------------
Columna: *** load_type ***:
['Dry Van' 'Refrigerated']
---------------------------------------
Columna: *** weight_lbs ***:
[19178 27761 35594 ... 23230 33014 27602]
---------------------------------------
Columna: *** pieces ***:
[13 22 16 10  4 26  3  8 20 17  1 12 24  5 18  9 28 23  6  2 19 15  7 27
 11 25 14 21]
---------------------------------------
Columna: *** revenue ***:
[3045.23 1224.48 7171.12 ... 3908.87 2018.31 4350.65]
---------------------------------------
Columna: *** fuel_surcharge ***:
[406.72  98.61 792.88 141.33 738.48 383.23 314.64 463.93 565.38 273.36
 153.34 451.8  189.    13.8  295.83 453.91 128.63 472.14 149.26 344.12
 161.53 555.52  15.64  40.08 357.25 504.32 309.24 185.6  209.79 255.36
  86.46 249.44 137.31 460.   114.3  708.51 344.52 499.18 216.92 537.81
 564.72 170.88  76.16 454.74 376.   590.24 187.6  814.37 228.76 891.82
 384.2  580.87 144.   524.7  131.28 276.3  419.43]
---------------------------------------
Columna: *** accessorial_charges ***:
[100   0  50  75 150 200]
---------------------------------------
Columna: *** load_status ***:
['Completed']
---------------------------------------
Columna: *** booking_type ***:
['Spot' 'Dedicated' 'Contract']
---------------------------------------
Columna: *** trip_id ***:
['TRIP00000001' 'TRIP00000002' 'TRIP00000003' ... 'TRIP00085408'
 'TRIP00085409' 'TRIP00085410']
---------------------------------------
Columna: *** driver_id ***:
['DRV00117' 'DRV00141' 'DRV00032' 'DRV00083' 'DRV00044' 'DRV00120'
 'DRV00055' 'DRV00065' 'DRV00129' 'DRV00029' 'DRV00132' 'DRV00088'
 'DRV00070' 'DRV00009' 'DRV00071' 'DRV00036' 'DRV00094' 'DRV00125'
 'DRV00142' 'DRV00118' 'DRV00066' 'DRV00114' 'DRV00082' 'DRV00053'
 'DRV00102' 'DRV00050' 'DRV00139' 'DRV00085' 'DRV00113' 'DRV00124'
 'DRV00018' 'DRV00033' 'DRV00112' 'DRV00020' 'DRV00026' 'DRV00023'
 'DRV00089' 'DRV00148' 'DRV00134' 'DRV00047' 'DRV00126' 'DRV00001'
 'DRV00121' 'DRV00108' 'DRV00041' 'DRV00104' 'DRV00079' 'DRV00003' nan
 'DRV00077' 'DRV00147' 'DRV00092' 'DRV00051' 'DRV00037' 'DRV00110'
 'DRV00014' 'DRV00060' 'DRV00013' 'DRV00039' 'DRV00035' 'DRV00078'
 'DRV00049' 'DRV00054' 'DRV00030' 'DRV00150' 'DRV00005' 'DRV00002'
 'DRV00109' 'DRV00084' 'DRV00111' 'DRV00090' 'DRV00075' 'DRV00127'
 'DRV00019' 'DRV00069' 'DRV00015' 'DRV00101' 'DRV00119' 'DRV00017'
 'DRV00103' 'DRV00105' 'DRV00012' 'DRV00043' 'DRV00098' 'DRV00107'
 'DRV00149' 'DRV00095' 'DRV00146' 'DRV00122' 'DRV00063' 'DRV00024'
 'DRV00087' 'DRV00045' 'DRV00145' 'DRV00074' 'DRV00133' 'DRV00056'
 'DRV00123' 'DRV00010' 'DRV00138' 'DRV00091' 'DRV00100' 'DRV00011'
 'DRV00059' 'DRV00004' 'DRV00099' 'DRV00006' 'DRV00022' 'DRV00097'
 'DRV00034' 'DRV00062' 'DRV00016' 'DRV00058' 'DRV00143' 'DRV00064'
 'DRV00080' 'DRV00128' 'DRV00028' 'DRV00057' 'DRV00144' 'DRV00038'
 'DRV00025' 'DRV00081' 'DRV00130' 'DRV00061']
---------------------------------------
Columna: *** truck_id ***:
['TRK00035' 'TRK00108' 'TRK00031' 'TRK00105' 'TRK00076' 'TRK00062'
 'TRK00002' 'TRK00014' 'TRK00116' 'TRK00085' 'TRK00039' 'TRK00086'
 'TRK00052' 'TRK00120' 'TRK00054' 'TRK00049' 'TRK00080' 'TRK00040'
 'TRK00010' 'TRK00058' 'TRK00078' 'TRK00026' 'TRK00001' 'TRK00018'
 'TRK00019' 'TRK00111' 'TRK00024' 'TRK00071' 'TRK00069' 'TRK00064'
 'TRK00009' 'TRK00038' 'TRK00089' 'TRK00020' 'TRK00079' 'TRK00061'
 'TRK00007' 'TRK00015' 'TRK00090' 'TRK00050' 'TRK00004' 'TRK00063'
 'TRK00073' 'TRK00030' 'TRK00115' 'TRK00043' 'TRK00082' 'TRK00112'
 'TRK00091' 'TRK00092' nan 'TRK00013' 'TRK00025' 'TRK00008' 'TRK00048'
 'TRK00098' 'TRK00051' 'TRK00067' 'TRK00059' 'TRK00096' 'TRK00072'
 'TRK00033' 'TRK00099' 'TRK00057' 'TRK00097' 'TRK00095' 'TRK00114'
 'TRK00011' 'TRK00065' 'TRK00045' 'TRK00029' 'TRK00016' 'TRK00083'
 'TRK00041' 'TRK00055' 'TRK00074' 'TRK00103' 'TRK00110' 'TRK00053'
 'TRK00012' 'TRK00101' 'TRK00084' 'TRK00060' 'TRK00107' 'TRK00093'
 'TRK00006' 'TRK00068' 'TRK00023' 'TRK00113' 'TRK00070' 'TRK00044'
 'TRK00106' 'TRK00036']
---------------------------------------
Columna: *** trailer_id ***:
['TRL00167' 'TRL00082' 'TRL00138' 'TRL00018' 'TRL00054' 'TRL00007'
 'TRL00093' 'TRL00148' 'TRL00083' 'TRL00126' 'TRL00142' 'TRL00119'
 'TRL00021' 'TRL00132' 'TRL00048' 'TRL00171' 'TRL00004' 'TRL00095'
 'TRL00062' 'TRL00151' 'TRL00061' 'TRL00027' 'TRL00081' 'TRL00024'
 'TRL00163' 'TRL00055' 'TRL00067' 'TRL00039' 'TRL00088' 'TRL00136'
 'TRL00174' 'TRL00153' 'TRL00084' 'TRL00100' 'TRL00097' 'TRL00120'
 'TRL00069' 'TRL00168' 'TRL00070' 'TRL00031' 'TRL00034' 'TRL00117'
 'TRL00086' 'TRL00149' 'TRL00005' 'TRL00064' 'TRL00170' 'TRL00072'
 'TRL00010' 'TRL00103' 'TRL00152' 'TRL00023' 'TRL00127' 'TRL00040'
 'TRL00131' 'TRL00162' 'TRL00105' 'TRL00141' 'TRL00113' 'TRL00092'
 'TRL00033' 'TRL00178' 'TRL00014' 'TRL00112' 'TRL00158' 'TRL00144'
 'TRL00087' 'TRL00074' 'TRL00176' 'TRL00002' 'TRL00056' 'TRL00096'
 'TRL00118' 'TRL00053' 'TRL00013' 'TRL00073' 'TRL00099' 'TRL00046'
 'TRL00025' 'TRL00001' 'TRL00111' 'TRL00104' 'TRL00077' 'TRL00110'
 'TRL00122' 'TRL00071' 'TRL00106' 'TRL00154' 'TRL00150' 'TRL00042'
 'TRL00079' 'TRL00029' 'TRL00137' 'TRL00089' 'TRL00090' 'TRL00164'
 'TRL00109' 'TRL00051' 'TRL00016' 'TRL00047' 'TRL00129' 'TRL00035'
 'TRL00177' 'TRL00020' 'TRL00032' 'TRL00030' 'TRL00006' 'TRL00060'
 'TRL00161' 'TRL00050' 'TRL00057' 'TRL00165' 'TRL00011' 'TRL00102'
 'TRL00003' 'TRL00125' 'TRL00022' 'TRL00008' 'TRL00036' 'TRL00065'
 'TRL00063' 'TRL00169' 'TRL00175' 'TRL00059' 'TRL00107' 'TRL00108'
 'TRL00043' 'TRL00012' 'TRL00028' 'TRL00172' 'TRL00160' 'TRL00052'
 'TRL00180' 'TRL00155' nan 'TRL00094' 'TRL00091' 'TRL00019' 'TRL00038'
 'TRL00145' 'TRL00156' 'TRL00009' 'TRL00123' 'TRL00080' 'TRL00133'
 'TRL00134' 'TRL00076' 'TRL00139' 'TRL00114' 'TRL00041' 'TRL00058'
 'TRL00049' 'TRL00115' 'TRL00066' 'TRL00015' 'TRL00026' 'TRL00037'
 'TRL00173' 'TRL00147' 'TRL00121' 'TRL00045' 'TRL00140' 'TRL00143'
 'TRL00017' 'TRL00101' 'TRL00124' 'TRL00128' 'TRL00044' 'TRL00075'
 'TRL00135' 'TRL00130' 'TRL00078' 'TRL00068' 'TRL00166' 'TRL00116'
 'TRL00157' 'TRL00179' 'TRL00159' 'TRL00085' 'TRL00098' 'TRL00146']
---------------------------------------
Columna: *** dispatch_date ***:
['2022-01-01' '2022-01-02' '2022-01-03' ... '2024-12-29' '2024-12-30'
 '2024-12-31']
---------------------------------------
Columna: *** actual_distance_miles ***:
[1314  515 2509 ... 3329 3381 2920]
---------------------------------------
Columna: *** actual_duration_hours ***:
[26.2  8.6 45.  11.1 35.  39.4 20.9 50.5 51.4 60.2  9.9 14.3 12.4 11.4
  1.9 25.5 25.8 44.7 10.3 48.  14.6 46.4 19.9 41.3  9.4  8.3 34.2 32.7
  1.6 11.9  3.2 40.9 42.8 26.5  9.6 57.7 45.5 32.   3.1 48.6 34.8  3.
 34.7 16.3 23.8  4.5 13.3 31.5 14.8  9.7 24.  33.9 13.1 27.7 10.6 21.4
 12.9 41.  10.8 21.1 40.  22.5 41.5 14.2 12.5 43.  38.  51.6 39.9 12.6
  9.1  4.7 21.  16.8 43.8 13.4 22.1 33.2  8.9 14.5 41.9 39.1 13.9 21.9
 20.3 38.6 50.1 53.5 22.2 18.5 49.2  1.4 33.  51.9 21.3 23.4 43.6 11.6
  1.7 35.9 29.2 12.1 22.9 23.9 46.2 12.3 24.1 37.8 12.7 31.1 38.8 41.7
 47.6 54.5 44.3 32.9 11.3 26.9 64.  46.  11.7 13.5  2.7 53.1 29.9 43.1
  5.  39.8 36.4  9.5  7.5 41.6 54.7 29.7 13.2 46.7  9.3  7.9 14.9 48.3
 20.2 38.5 54.  46.6 37.9 51.1 21.2 24.8 30.2 26.6 12.  20.4 20.7 17.7
 11.8 18.9 31.8 10.9 33.7  7.8 38.9 24.7 17.  42.4 51.7 18.2 31.7 17.8
 28.  33.1 18.4 25.9 14.7 37.7 19.5 42.3 36.8 23.2 13.6 39.5 49.9 14.4
 15.  11.5 31.3 35.7 26.3 33.8 44.2  9.8 36.7 23.7 10.4 30.5 14.  37.3
 10.7 35.2 30.4 25.4 43.5 53.3 37.2 43.7 30.8 34.6 47.3 15.9 31.6 27.5
 20.5  4.4 32.8 16.1 45.1 18.7 43.4 20.8 20.6  2.6 48.8 20.  18.  47.2
 41.8 24.9 37.6 24.6 33.6  2.8 34.5  2.9 19.4  4.9 22.7 29.  46.1 28.5
 12.2 37.5  8.5 45.7 38.7 44.8 25.7 42.1 42.   9.  35.3 37.  47.4 27.9
 46.9 20.1 40.1 45.2 36.2 43.2 40.7 24.2 14.1 11.  15.7  8.1 31.2 19.8
 16.6 39.7 26.8 10.1 51.5 48.2 34.4 29.5 25.2 44.5 58.4 27.1 10.   1.8
 42.7 10.2 23.3 23.1 52.6 28.8 50.9 61.8 34.3  1.5 57.1 24.3 21.7 37.1
 52.  52.2 28.9  8.8  8.  47.   4.2 44.1 44.4  5.2 62.8 36.3 13.  50.3
 15.3 53.4 41.4 52.1 23.6 22.6 27.3 19.2 23.5 43.9 12.8 21.6 18.8 29.6
 30.1 15.4  8.4 64.1 53.7 34.  27.4 53.2 32.2 47.7 40.2 42.9 34.1 23.
 49.3 16.2 34.9 44.  40.5 32.4 35.8 31.4 15.5 56.  24.4 30.3 27.6 46.5
 11.2 48.9  3.6 18.6 19.  58.5 28.4 16.5  3.3 56.4 16.9 45.4  8.7  4.8
 54.3  4.3 58.1 10.5 38.1 25.3 29.4 16.4 46.3 35.4 26.7 58.  19.3 45.9
 16.7 31.9 27.  54.8 42.5 13.8 33.4 50.4 30.6 39.3  7.7 51.3 40.3 24.5
 25.6 37.4 19.6 15.6 39.2 15.2 36.  36.1 55.1  5.1  5.3 50.2 38.2 44.6
  4.6 13.7 47.8 35.1 36.5 44.9 38.4 25.  30.  15.1 49.6 22.3 48.7 48.4
 36.6 48.5 32.6 63.  51.  39.6 17.9  8.2 42.6 49.4 22.4 38.3 32.5 42.2
 58.2 35.5 29.8 19.1 47.9 55.5 39.  28.6 21.8 15.8 28.2 56.3 25.1  9.2
 45.8 41.2 55.4 17.4 58.9 17.3 40.6  5.4 31.  43.3 49.  35.6 60.5 30.9
 53.8 49.1 32.1 45.3 47.1 22.  33.5 26.1 55.  29.1 17.6 50.  17.1 18.3
 19.7 22.8 59.5 51.2 21.5 49.5 52.8 57.5 40.8 52.3 41.1 55.9 50.7 28.7
 32.3 26.  56.1 54.1 33.3 29.3 62.5 52.7 28.3 26.4 65.7 65.1 45.6 51.8
 27.2 17.5 50.8 46.8 40.4 47.5 52.5 55.6 27.8 63.2 17.2 36.9 16.  49.7
 57.3 30.7 59.9 58.6  3.4 56.7 54.4  3.5 18.1 50.6 28.1 60.8  7.4 52.9
 65.4 53.9 58.3  4.1 49.8 55.8 53.  66.1 57.  61.3 59.6 48.1 53.6 61.6
 58.8 59.7 56.6 55.3 56.9 54.9 60.  61.7  2.  61.4 64.3 62.3 52.4 62.7
 61.1 56.2 54.6  2.5 64.6 60.6  7.6  4.  58.7 59.1 57.2 59.2 55.2 57.4
 54.2 61.9 62.9  7.3 57.9 63.1 66.2 65.8 56.8 60.7 57.8 57.6  7.2 66.
 61.2 59.4 60.1 66.7 62.  60.9 64.4 61.  64.5 62.6 63.6 64.2 62.2 56.5
 64.8  5.5 63.9 55.7 61.5 63.8 65.2 60.3 64.7 62.1 59.  66.9 59.3 62.4
 59.8 60.4 63.5 63.3 63.4 64.9 65.3 67.8 66.5 65.5 63.7  5.6 65.  67.1
 67.  65.9]
---------------------------------------
Columna: *** fuel_gallons_used ***:
[183.8  93.6 339.1 ... 604.7 550.3 538.5]
---------------------------------------
Columna: *** average_mpg ***:
[7.15 5.5  7.4  6.5  6.82 5.51 5.85 6.28 6.93 7.36 7.45 5.73 6.15 5.98
 6.62 7.49 7.3  6.59 7.17 6.32 6.57 6.33 6.49 6.12 6.3  5.94 7.47 5.7
 6.25 7.11 6.26 6.81 6.64 6.14 6.24 5.61 7.08 7.33 6.61 5.52 7.32 5.95
 7.43 7.39 6.51 6.31 6.27 7.46 6.76 6.18 6.74 6.54 6.68 7.34 6.48 5.82
 6.67 7.01 6.65 6.56 5.69 5.6  6.45 6.01 6.04 6.85 6.73 6.88 6.42 7.04
 5.54 5.71 7.21 7.07 7.12 6.71 7.2  6.99 7.23 5.8  5.89 5.83 6.37 5.97
 5.74 6.16 6.1  7.28 7.24 7.02 5.64 5.91 6.09 5.68 5.59 6.69 6.43 7.05
 6.6  7.42 5.88 6.78 7.1  5.87 7.06 5.58 7.09 6.63 7.16 6.52 6.08 6.41
 6.38 6.17 5.67 6.77 6.22 6.46 6.03 5.76 6.87 6.72 6.19 6.13 6.92 5.79
 6.95 5.92 5.62 6.98 6.29 6.75 7.48 5.78 5.93 5.84 6.94 6.39 7.35 5.96
 7.31 5.86 7.38 6.35 6.84 6.07 7.29 5.72 7.26 6.91 5.55 6.44 6.02 6.7
 7.18 6.05 5.77 6.9  6.97 5.65 7.37 6.89 5.53 5.9  7.22 6.36 7.27 5.56
 5.99 6.83 6.55 6.   5.57 6.86 5.63 7.03 6.11 6.06 7.25 6.66 6.47 7.14
 6.53 7.13 6.58 7.41 6.34 7.5  6.2  6.4  7.19 6.23 5.66 5.81 6.96 6.21
 6.8  7.   5.75 7.44 6.79]
---------------------------------------
Columna: *** idle_time_hours ***:
[ 3.5  8.3 12.   9.6 11.6  6.6  2.3 10.5  4.1  5.7  4.9  6.7  3.6  8.7
  4.4  8.8  5.9  3.7  8.1  6.1  9.7  9.8  3.9  3.1  4.3  2.  10.6 11.9
  5.1  6.9 10.9 11.   6.5  7.  11.5 11.7  7.8  9.9  2.7  4.6  7.3  2.8
  2.2  5.4  7.5  9.2  5.8 10.2  4.   3.   5.5  5.3  8.4  4.5  6.8  3.8
 10.3  6.   6.2 11.3  8.5  4.2  7.9  2.9 10.1  4.7  6.4  3.3  2.4 11.4
  9.3  4.8 10.8  9.4  7.1  2.5  2.6  3.2 10.7  5.6  9.1  6.3  3.4  7.7
 11.2  8.2  8.6  8.   8.9  9.5  7.2 10.4 11.8 11.1  2.1  5.   9.   7.4
 10.   5.2  7.6]
---------------------------------------
Columna: *** trip_status ***:
['Completed']
---------------------------------------
Los valores duplicados en la columna load_id es de 0
---------------------------------------
Los valores duplicados en la columna trip_id es de 0

#### <span style="color:orange">**Limpieza de columnas** <br>
<span style="color:orange">Dentro de este archivo, hay columnas que no sirven para el análisis, y para que no ocupen espacio y no perjudique al rendimiento, las eliminamos. <br>Otras en cambio, vamos a añadirlas, como total_revenue, para utilizarla en el análisis más adelante
<span>

In [96]:
df.drop(columns=['load_id', 'trip_id', 'load_status','trip_status'], inplace=True)
df['total_revenue'] = df['revenue'] - df['accessorial_charges'] - df['fuel_surcharge']
df.sample(5)

,customer_id,route_id,load_date,load_type,weight_lbs,pieces,revenue,fuel_surcharge,accessorial_charges,booking_type,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,total_revenue
70923,CUST00195,RTE00022,2024-06-29,Refrigerated,27876,16,1130.65,161.53,100,Contract,DRV00013,TRK00055,TRL00083,2024-06-29,590,9.4,100.9,5.85,9.9,869.12
18176,CUST00069,RTE00028,2022-08-20,Refrigerated,19444,5,3816.47,564.72,75,Spot,DRV00088,TRK00071,TRL00005,2022-08-20,2298,40.7,324.1,7.09,5.6,3176.75
19303,CUST00079,RTE00057,2022-09-04,Refrigerated,19487,8,2102.81,276.30,75,Spot,DRV00118,TRK00111,TRL00100,2022-09-04,974,16.7,132.0,7.38,4.3,1751.51
77690,CUST00116,RTE00052,2024-09-24,Refrigerated,40433,7,1133.06,273.36,100,Dedicated,DRV00056,TRK00108,TRL00147,2024-09-24,792,15.2,126.1,6.28,10.3,759.70
44890,CUST00003,RTE00040,2023-07-30,Dry Van,35025,14,3602.88,524.70,0,Contract,DRV00015,TRK00012,TRL00029,2023-07-30,1766,27.8,302.4,5.84,6.8,3078.18

#### <span style="color:orange">**Limpieza de duplicados**
<span style="color:orange">no encontramos duplicados

In [97]:
df.duplicated().sum()

np.int64(0)

#### <span style="color:orange">**Limpieza de nulos**
<span style="color:orange">Guardamos el archivo **df.csv** <br>
De momento no tocamos los nulos, pero los dejamos identificados

In [98]:
df.isna().sum()

customer_id                 0
route_id                    0
load_date                   0
load_type                   0
weight_lbs                  0
pieces                      0
revenue                     0
fuel_surcharge              0
accessorial_charges         0
booking_type                0
driver_id                1714
truck_id                 1672
trailer_id               1680
dispatch_date               0
actual_distance_miles       0
actual_duration_hours       0
fuel_gallons_used           0
average_mpg                 0
idle_time_hours             0
total_revenue               0
dtype: int64

In [99]:
df.to_csv('../datos_transformados/df_loads_trips.csv')

## <span style="color:orange">---------  Archivo *df_empleados.csv*  ---------
<span style="color:orange">Creamos este archivo para dar respuesta a los tres primeros puntos que nos pide el cliente: <br>
<span style="color:orange">- *1. Los 10 empleados que más viajes han realizado* <br>
<span style="color:orange">- *2. Los 10 empleados que más beneficios han reportado a la empresa* <br>
<span style="color:orange">- *3. Los 10 empleados que más tiempo han estado en la carretera*<span>

In [100]:
df_empleados = df.copy(deep=True) # deep=True para que se copie y sea un archivo independiente

<span style="color:orange">Eliminamos las columnas que no vamos a necesitar

In [101]:
df_empleados.drop(columns=['customer_id', 'route_id', 'load_date', 
                           'load_type', 'weight_lbs', 
                           'weight_lbs', 'pieces', 'booking_type',
                           'truck_id', 'trailer_id', 'fuel_gallons_used',
                           'average_mpg', ], inplace=True)

In [102]:
df_empleados.columns

Index(['revenue', 'fuel_surcharge', 'accessorial_charges', 'driver_id',
       'dispatch_date', 'actual_distance_miles', 'actual_duration_hours',
       'idle_time_hours', 'total_revenue'],
      dtype='object')

<span style="color:orange">Para este archivo (df_empleados), nos quedamos solo con los viajes realizados en el año 2024 >> nos quedamos solo con el año y descartamos mes y día

In [103]:
df_empleados["dispatch_date"] = pd.to_datetime(df_empleados["dispatch_date"])
df_empleados['dispatch_date_year'] = df_empleados['dispatch_date'].dt.year
df_empleados = df_empleados[df_empleados['dispatch_date_year'] == 2024]
df_empleados.drop(columns=['dispatch_date'], inplace=True)
df_empleados.sample(5)

,revenue,fuel_surcharge,accessorial_charges,driver_id,actual_distance_miles,actual_duration_hours,idle_time_hours,total_revenue,dispatch_date_year
58932,1339.52,273.36,75,DRV00056,835,14.2,6.5,991.16,2024
79696,3570.66,357.25,75,DRV00101,1500,24.4,6.4,3138.41,2024
64734,1133.92,161.53,100,DRV00022,598,9.7,6.8,872.39,2024
84197,7244.65,453.91,0,DRV00034,2531,46.3,9.8,6790.74,2024
57814,5464.03,472.14,200,DRV00138,2733,44.2,6.3,4791.89,2024

<span style="color:orange">Revisamos la columna driver_id, por si hay nulos, eliminarlos, y guardamos el archivo para el futuro análisis

In [104]:
df_empleados['driver_id'].isna().sum()
df_empleados.dropna(subset=["driver_id"], inplace=True)
df_empleados.to_csv('../datos_transformados/df_empleados.csv')

## <span style="color:orange">Archivo *df_rutas.csv*
<span style="color:orange">Cargamos el archivo para echar un vistazo y guardarlo para más adelante

<span style="color:orange">- *4. Qué rutas aportan mayores beneficios*

In [105]:
df_rutas = pd.read_csv('../datos_en_bruto/routes.csv', sep = ',')

print(f'El número de filas que tenemos en df_rutas es {df_rutas.shape[0]}, y el número de columnas es {df_rutas.shape[1]}')

# Nombre de las columnas
sep()
print('df_rutas:\n', df_rutas.columns)

El número de filas que tenemos en df_rutas es 58, y el número de columnas es 9
---------------------------------------
df_rutas:
 Index(['route_id', 'origin_city', 'origin_state', 'destination_city',
       'destination_state', 'typical_distance_miles', 'base_rate_per_mile',
       'fuel_surcharge_rate', 'typical_transit_days'],
      dtype='object')

<span style="color:orange">Revisión de los tipos de datos, duplicados en route_id y nulos

In [106]:
df_rutas.info()
revisar_duplicados(df_rutas, 'route_id')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   route_id                58 non-null     object
 1   origin_city             58 non-null     object
 2   origin_state            58 non-null     object
 3   destination_city        58 non-null     object
 4   destination_state       58 non-null     object
 5   typical_distance_miles  58 non-null     int64
 6   base_rate_per_mile      58 non-null     float64
 7   fuel_surcharge_rate     58 non-null     float64
 8   typical_transit_days    58 non-null     int64
dtypes: float64(2), int64(2), object(5)
memory usage: 4.2+ KB
---------------------------------------
Los valores duplicados en la columna route_id es de 0

<span style="color:orange">Revisamos datos únicos de las columnas

In [107]:
for col in df_rutas.columns:
    sep()
    print(f'Columna: *** {col} ***:')
    print(df_rutas[col].unique())

---------------------------------------
Columna: *** route_id ***:
['RTE00001' 'RTE00002' 'RTE00003' 'RTE00004' 'RTE00005' 'RTE00006'
 'RTE00007' 'RTE00008' 'RTE00009' 'RTE00010' 'RTE00011' 'RTE00012'
 'RTE00013' 'RTE00014' 'RTE00015' 'RTE00016' 'RTE00017' 'RTE00018'
 'RTE00019' 'RTE00020' 'RTE00021' 'RTE00022' 'RTE00023' 'RTE00024'
 'RTE00025' 'RTE00026' 'RTE00027' 'RTE00028' 'RTE00029' 'RTE00030'
 'RTE00031' 'RTE00032' 'RTE00033' 'RTE00034' 'RTE00035' 'RTE00036'
 'RTE00037' 'RTE00038' 'RTE00039' 'RTE00040' 'RTE00041' 'RTE00042'
 'RTE00043' 'RTE00044' 'RTE00045' 'RTE00046' 'RTE00047' 'RTE00048'
 'RTE00049' 'RTE00050' 'RTE00051' 'RTE00052' 'RTE00053' 'RTE00054'
 'RTE00055' 'RTE00056' 'RTE00057' 'RTE00058']
---------------------------------------
Columna: *** origin_city ***:
['Atlanta' 'Chicago' 'Dallas' 'New York' 'Phoenix' 'Philadelphia'
 'Houston' 'Miami' 'Detroit' 'Seattle' 'Denver' 'Portland' 'Las Vegas'
 'Minneapolis' 'Charlotte' 'Columbus' 'Memphis' 'Kansas City']
---------------------------------------
Columna: *** origin_state ***:
['GA' 'IL' 'TX' 'NY' 'AZ' 'PA' 'FL' 'MI' 'WA' 'CO' 'OR' 'NV' 'MN' 'NC'
 'OH' 'TN' 'MO']
---------------------------------------
Columna: *** destination_city ***:
['Chicago' 'Miami' 'Los Angeles' 'Portland' 'Las Vegas' 'Charlotte'
 'New York' 'Denver' 'Indianapolis' 'Philadelphia' 'Columbus'
 'Kansas City' 'Seattle' 'Minneapolis' 'Detroit' 'Memphis' 'Dallas'
 'Houston' 'Atlanta']
---------------------------------------
Columna: *** destination_state ***:
['IL' 'FL' 'CA' 'OR' 'NV' 'NC' 'NY' 'CO' 'IN' 'PA' 'OH' 'MO' 'WA' 'MN'
 'MI' 'TN' 'TX' 'GA']
---------------------------------------
Columna: *** typical_distance_miles ***:
[ 677  697 2003 2017 1749  675 1576  762  878   92  547 2389  673 1204
 2729 1130  670 1271 2172 2108  557 1276 1175 3141 1984 2623 2147  640
 2259  167 2332 1229  262 2561 1311 1044 1216 1559 2627  597 2269  476
  720  712 1840  804  777 1557 1429 1718  921  519]
---------------------------------------
Columna: *** base_rate_per_mile ***:
[1.7  2.08 2.55 1.84 2.41 2.13 2.54 2.62 1.95 1.61 1.69 2.71 2.14 2.79
 2.5  1.81 2.07 2.33 1.77 2.45 2.48 1.65 1.72 2.02 1.89 2.47 2.19 1.99
 2.42 2.12 2.63 1.52 2.38 2.75 2.39 1.55 2.69 2.74 2.06 1.94 1.85 1.63
 2.35 2.01 2.51 2.27]
---------------------------------------
Columna: *** fuel_surcharge_rate ***:
[0.19 0.22 0.29 0.26 0.28 0.32 0.15 0.17 0.24 0.21 0.34 0.18 0.33 0.2
 0.3  0.16 0.31 0.23 0.25 0.27]
---------------------------------------
Columna: *** typical_transit_days ***:
[1 3 2 4 5]

In [108]:
df_rutas.sample(10)

,route_id,origin_city,origin_state,destination_city,destination_state,typical_distance_miles,base_rate_per_mile,fuel_surcharge_rate,typical_transit_days
34,RTE00035,Las Vegas,NV,Dallas,TX,1229,1.69,0.28,2
51,RTE00052,Memphis,TN,Minneapolis,MN,804,1.63,0.34,1
27,RTE00028,Seattle,WA,Houston,TX,2172,1.89,0.26,3
13,RTE00014,Phoenix,AZ,Kansas City,MO,1204,2.14,0.19,2
36,RTE00037,Las Vegas,NV,New York,NY,2561,1.52,0.21,4
14,RTE00015,Philadelphia,PA,New York,NY,92,2.79,0.15,1
40,RTE00041,Minneapolis,MN,Houston,TX,1216,2.75,0.21,2
20,RTE00021,Houston,TX,Portland,OR,2108,2.45,0.28,3
25,RTE00026,Miami,FL,Denver,CO,1984,1.72,0.28,3
42,RTE00043,Charlotte,NC,Denver,CO,1559,1.55,0.16,2

<span style="color:orange">Guardamos para su posterior análisis

In [109]:
df_rutas.to_csv('../datos_transformados/df_rutas.csv', index=False)

## <span style="color:orange">Archivos *df_camiones.csv*, *df_camiones_metricas.csv* y *df_camiones_mantenimiento.csv*<span>

<span style="color:orange">- *5. Qué camiones y trailers tienen un mantenimiento más costoso*

In [110]:
df_camiones = pd.read_csv('../datos_en_bruto/trucks.csv', sep=',')
df_camiones_metricas = pd.read_csv('../datos_en_bruto/truck_utilization_metrics.csv', sep=',')
df_camiones_mantenimiento = pd.read_csv('../datos_en_bruto/maintenance_records.csv', sep=',')

print (f'El número de filas que tenemos en df_camiones es {df_camiones.shape[0]}, y el número de columnas es {df_camiones.shape[1]}')
print (f'El número de filas que tenemos en df_camiones_metricas es {df_camiones_metricas.shape[0]}, y el número de columnas es {df_camiones_metricas.shape[1]}')
print (f'El número de filas que tenemos en df_camiones_mantenimiento es {df_camiones_mantenimiento.shape[0]}, y el número de columnas es {df_camiones_mantenimiento.shape[1]}')

El número de filas que tenemos en df_camiones es 120, y el número de columnas es 11
El número de filas que tenemos en df_camiones_metricas es 3312, y el número de columnas es 10
El número de filas que tenemos en df_camiones_mantenimiento es 2920, y el número de columnas es 12

<span style="color:orange">Nombre de las columnas de los archivos

In [111]:
print('df_camiones:\n', df_camiones.columns)
sep()
print('df_camiones_metricas:\n', df_camiones_metricas.columns)
sep()
print('df_camiones_mantenimiento:\n', df_camiones_mantenimiento.columns)

df_camiones:
 Index(['truck_id', 'unit_number', 'make', 'model_year', 'vin',
       'acquisition_date', 'acquisition_mileage', 'fuel_type',
       'tank_capacity_gallons', 'status', 'home_terminal'],
      dtype='object')
---------------------------------------
df_camiones_metricas:
 Index(['truck_id', 'month', 'trips_completed', 'total_miles', 'total_revenue',
       'average_mpg', 'maintenance_events', 'maintenance_cost',
       'downtime_hours', 'utilization_rate'],
      dtype='object')
---------------------------------------
df_camiones_mantenimiento:
 Index(['maintenance_id', 'truck_id', 'maintenance_date', 'maintenance_type',
       'odometer_reading', 'labor_hours', 'labor_cost', 'parts_cost',
       'total_cost', 'facility_location', 'downtime_hours',
       'service_description'],
      dtype='object')

In [112]:
df_camiones.sample(5)

,truck_id,unit_number,make,model_year,vin,acquisition_date,acquisition_mileage,fuel_type,tank_capacity_gallons,status,home_terminal
50,TRK00051,8355,Mack,2016,1MT877433803899130,2018-05-19,27475,Diesel,250,Active,Columbus
90,TRK00091,7495,International,2015,1VT853515078943231,2016-12-13,14486,Diesel,250,Active,Charlotte
112,TRK00113,1311,Mack,2015,1MT674631830199518,2018-04-02,27284,Diesel,200,Active,Seattle
46,TRK00047,6968,Mack,2015,1MT808220883834648,2015-09-06,47515,Diesel,150,Maintenance,Phoenix
97,TRK00098,4678,Peterbilt,2018,1NT233108199589879,2019-03-24,48182,Diesel,150,Active,Charlotte

In [113]:
df_camiones_metricas.sample(5)

,truck_id,month,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
2016,TRK00072,2022-01-01,20,33590,71888.44,6.35,2,2144.16,15.4,0.645
1805,TRK00065,2022-06-01,22,35585,70070.86,6.75,1,718.27,10.3,0.733
2471,TRK00089,2023-12-01,24,34108,72340.35,6.40,0,0.00,0.0,0.774
1440,TRK00054,2022-01-01,29,44491,97598.19,6.57,1,514.72,14.0,0.935
587,TRK00020,2022-12-01,30,44990,102197.20,6.44,0,0.00,0.0,0.968

In [114]:
df_camiones_mantenimiento.sample(5)

,maintenance_id,truck_id,maintenance_date,maintenance_type,odometer_reading,labor_hours,labor_cost,parts_cost,total_cost,facility_location,downtime_hours,service_description
1493,MAINT00001494,TRK00072,2023-07-03,Brake,584936,7.1,886.49,880.04,1766.53,New York,37.7,Routine Brake
1242,MAINT00001243,TRK00089,2023-04-05,Tire,366339,7.5,697.16,2390.96,3088.12,Milwaukee,37.6,Scheduled Tire
738,MAINT00000739,TRK00060,2022-10-01,Inspection,129855,6.6,818.60,74.42,893.02,Philadelphia,27.8,Scheduled Inspection
1522,MAINT00001523,TRK00028,2023-07-12,Preventive,277480,4.5,450.80,2309.99,2760.79,Memphis,8.8,Emergency Preventive
2287,MAINT00002288,TRK00025,2024-04-29,Engine,300033,5.9,720.70,2138.09,2858.79,Columbus,4.9,Emergency Engine

<span style="color:orange">Revisamos los datos únicos de las columnas

In [115]:
for col in df_camiones.columns:
    sep()
    print(f'Columna: *** {col} ***:')
    print(df_camiones[col].unique())

---------------------------------------
Columna: *** truck_id ***:
['TRK00001' 'TRK00002' 'TRK00003' 'TRK00004' 'TRK00005' 'TRK00006'
 'TRK00007' 'TRK00008' 'TRK00009' 'TRK00010' 'TRK00011' 'TRK00012'
 'TRK00013' 'TRK00014' 'TRK00015' 'TRK00016' 'TRK00017' 'TRK00018'
 'TRK00019' 'TRK00020' 'TRK00021' 'TRK00022' 'TRK00023' 'TRK00024'
 'TRK00025' 'TRK00026' 'TRK00027' 'TRK00028' 'TRK00029' 'TRK00030'
 'TRK00031' 'TRK00032' 'TRK00033' 'TRK00034' 'TRK00035' 'TRK00036'
 'TRK00037' 'TRK00038' 'TRK00039' 'TRK00040' 'TRK00041' 'TRK00042'
 'TRK00043' 'TRK00044' 'TRK00045' 'TRK00046' 'TRK00047' 'TRK00048'
 'TRK00049' 'TRK00050' 'TRK00051' 'TRK00052' 'TRK00053' 'TRK00054'
 'TRK00055' 'TRK00056' 'TRK00057' 'TRK00058' 'TRK00059' 'TRK00060'
 'TRK00061' 'TRK00062' 'TRK00063' 'TRK00064' 'TRK00065' 'TRK00066'
 'TRK00067' 'TRK00068' 'TRK00069' 'TRK00070' 'TRK00071' 'TRK00072'
 'TRK00073' 'TRK00074' 'TRK00075' 'TRK00076' 'TRK00077' 'TRK00078'
 'TRK00079' 'TRK00080' 'TRK00081' 'TRK00082' 'TRK00083' 'TRK00084'
 'TRK00085' 'TRK00086' 'TRK00087' 'TRK00088' 'TRK00089' 'TRK00090'
 'TRK00091' 'TRK00092' 'TRK00093' 'TRK00094' 'TRK00095' 'TRK00096'
 'TRK00097' 'TRK00098' 'TRK00099' 'TRK00100' 'TRK00101' 'TRK00102'
 'TRK00103' 'TRK00104' 'TRK00105' 'TRK00106' 'TRK00107' 'TRK00108'
 'TRK00109' 'TRK00110' 'TRK00111' 'TRK00112' 'TRK00113' 'TRK00114'
 'TRK00115' 'TRK00116' 'TRK00117' 'TRK00118' 'TRK00119' 'TRK00120']
---------------------------------------
Columna: *** unit_number ***:
[3463 6461 2335 3317 6731 6082 7421 3112 2388 6072 7171 6381 3093 9624
 2531 7937 9331 6928 1298 6940 6060 3953 4509 6598 8967 4145 4711 3253
 3538 2264 5846 2657 9317 9843 9626 1618 6517 3147 7172 3527 3658 3962
 3712 8170 1715 7731 6968 4891 8277 5668 8355 4833 9749 4918 6070 8684
 4178 7026 8218 8564 5616 7256 9239 9641 7859 3655 4271 3267 5096 1854
 8873 7081 2680 9452 3042 5670 2374 3626 5469 8361 9410 3414 8167 2502
 4637 8391 6727 1436 7797 1872 7495 9224 7126 4862 7326 2337 7142 4678
 1461 6221 2623 6493 3392 3254 1627 5700 8740 3273 8685 8349 1086 2298
 1311 5193 4533 3449 9991 9647 7934 2821]
---------------------------------------
Columna: *** make ***:
['Peterbilt' 'Kenworth' 'Freightliner' 'Volvo' 'Mack' 'International']
---------------------------------------
Columna: *** model_year ***:
[2016 2015 2018 2017 2019 2021 2020]
---------------------------------------
Columna: *** vin ***:
['1VV205190335317039' '1NV753749606229960' '1NT803101860493229'
 '1VV131945381692351' '1FT822215709701985' '1VV963516965177788'
 '1MV134100489809236' '1MV426140684859204' '1VU871233565012431'
 '1MU182160377362421' '1FT567947164925037' '1MU483021764762154'
 '1NU908806171429154' '1VV247228896414388' '1VV219552826957760'
 '1VT237947763097353' '1VU258614207044782' '1FT570778303307847'
 '1NT468662011712903' '1VT279404061535276' '1MV661551799038494'
 '1VU201382802563540' '1MV342228599481462' '1VT416775529985868'
 '1MV857192659408369' '1MU109206419984555' '1FU919098643889893'
 '1VU150939883819521' '1MT732548052826703' '1NU424938126853269'
 '1FU607053119824892' '1VV787975078730489' '1FT208855839098628'
 '1MU728063113988930' '1VT778313629938960' '1MV151007204500818'
 '1FT474970889663627' '1MV267690370888657' '1NU790256784273010'
 '1VT932401669552606' '1VV671184850440720' '1MV437535307599343'
 '1MT472942182331015' '1FU446413094240484' '1FV398961826922119'
 '1NV756988482935978' '1MT808220883834648' '1MT866431853044978'
 '1NT223732426577573' '1NT453185644930902' '1MT877433803899130'
 '1NU972541941349939' '1MV170122760242723' '1NV731502816958608'
 '1VV691633799611733' '1MU294987034236724' '1MV715049377005134'
 '1VV866452895220495' '1VV316468431256116' '1NU436079292908621'
 '1NU425390034513228' '1NV650570590608475' '1VU731052452964922'
 '1VU745675841954861' '1MU488586386042743' '1NU423840714792581'
 '1FU598074146039095' '1VV340928248098898' '1NV883821060467126'
 '1VT793191010829814' '1NT854162115475075' '1NV159099750018373'
 '1FU907674313580395' '1MT967805362821388' '1NT719643369337760'
 '1NU637560149881760' '1NU421346537524210' '1FT746416854486193'
 '1NV914157173264203' '1FT297919985452583' '1FU657752132291004'
 '1NV425914685665284' '1FT739466077384341' '1FU611549007005766'
 '1MT667695252589838' '1MU472314018835209' '1NV829905893174057'
 '1VV115857818975755' '1VU859309706861616' '1NT680153134413264'
 '1VT853515078943231' '1FT258316710836362' '1MU379279972794550'
 '1FU365172928294515' '1MU471127926628434' '1VV745004113400907'
 '1FU504820655065872' '1NT233108199589879' '1MU556456925295542'
 '1VV819124058535238' '1VU348655476430824' '1NT272470760513799'
 '1MV782002103958545' '1VU718383816155959' '1MV847705711168299'
 '1NT949762201559873' '1FV694670205670221' '1VT735199537843337'
 '1FT716597654505822' '1NV268717210259310' '1NU685854389033038'
 '1MT331261140931634' '1MT674631830199518' '1MT248556276310965'
 '1MU165006752005085' '1MV446968103715126' '1FU939700479057712'
 '1NV150990165397549' '1MU171789091515507' '1FT135731860465802']
---------------------------------------
Columna: *** acquisition_date ***:
['2017-04-27' '2018-10-04' '2020-09-17' '2017-06-17' '2021-10-08'
 '2018-05-12' '2020-01-29' '2015-01-27' '2016-11-04' '2017-12-11'
 '2021-01-06' '2017-02-08' '2020-10-25' '2019-04-11' '2017-02-12'
 '2015-05-26' '2017-07-06' '2016-02-16' '2021-02-13' '2017-07-25'
 '2018-07-11' '2018-03-13' '2019-07-09' '2018-04-08' '2020-02-13'
 '2021-02-23' '2016-04-12' '2020-09-21' '2016-01-20' '2016-04-14'
 '2019-10-30' '2018-01-31' '2018-01-24' '2020-05-07' '2019-05-10'
 '2020-11-06' '2020-05-12' '2019-02-18' '2019-10-16' '2020-01-22'
 '2015-04-01' '2020-04-15' '2021-02-27' '2020-01-07' '2016-06-18'
 '2016-10-19' '2015-09-06' '2015-07-04' '2016-12-20' '2015-09-03'
 '2018-05-19' '2018-06-17' '2020-04-23' '2017-01-26' '2021-03-28'
 '2016-09-29' '2017-01-16' '2018-08-10' '2018-12-03' '2015-05-16'
 '2021-05-16' '2018-01-21' '2016-04-24' '2021-03-04' '2018-07-10'
 '2016-10-28' '2016-12-07' '2021-07-31' '2021-05-13' '2017-11-13'
 '2018-10-14' '2021-02-21' '2020-12-28' '2015-02-08' '2015-05-05'
 '2016-04-26' '2017-09-10' '2016-10-24' '2015-06-30' '2015-10-15'
 '2021-07-17' '2016-12-16' '2015-08-05' '2019-11-22' '2018-05-26'
 '2015-03-21' '2016-09-01' '2016-05-19' '2020-04-24' '2021-04-23'
 '2016-12-13' '2020-11-04' '2018-02-25' '2021-01-21' '2016-05-06'
 '2020-01-26' '2021-07-25' '2019-03-24' '2017-02-03' '2017-01-28'
 '2016-02-21' '2015-03-02' '2020-03-22' '2017-12-03' '2017-10-27'
 '2018-10-31' '2017-08-29' '2017-06-02' '2018-03-18' '2015-04-20'
 '2021-06-01' '2018-04-02' '2021-04-07' '2018-04-22' '2020-12-10'
 '2015-09-30' '2017-09-01' '2018-10-26' '2019-03-06']
---------------------------------------
Columna: *** acquisition_mileage ***:
[18814 26795 11795  8875 42042 47794 42328 27548 24540 25066 29395 24739
 24618  5259 44743 43371 35343  8715 42830 22791  7774 11696 35209 25759
 34658  8345 47700 14594   227 49556  1489 19553 30343 44138 47126 35680
 27795 34860 24856 15051 16220 30187 22685 10166 18064 12352 47515  7395
  2111 43266 27475 40299  1025 15772 13505  4409  6612 38924  2200 29257
 39176 44041 46090  3190 16038 48532  2899 26362 28767 15357 35373 14238
 49439  3699  9183 33023 18957 15346 47940 37755 20899 37845 39185 44075
 21015 15525 19776  9388 43267 34160 14486 27103 19693 18032  3994 36485
 38775 48182 11477 41025 44482 27997 36428 32481  3072 22571 42160 43997
 24979 34371 20888 45633 27284 26755  9779 19653 24671 12050 49441 35253]
---------------------------------------
Columna: *** fuel_type ***:
['Diesel']
---------------------------------------
Columna: *** tank_capacity_gallons ***:
[200 150 250]
---------------------------------------
Columna: *** status ***:
['Active' 'Maintenance' 'Inactive']
---------------------------------------
Columna: *** home_terminal ***:
['Omaha' 'Seattle' 'Atlanta' 'Salt Lake City' 'Miami' 'Minneapolis'
 'Charlotte' 'Houston' 'Denver' 'Columbus' 'Portland' 'Las Vegas'
 'Phoenix' 'Nashville' 'Memphis' 'Dallas' 'Kansas City' 'Detroit'
 'Milwaukee' 'New York' 'Oklahoma City' 'Los Angeles' 'Indianapolis'
 'Philadelphia']

<span style="color:orange">Eliminamos la columna fuel_type, ya que solo hay un valor único, y revisamos si en la columna truck_id hay duplicados<span>

In [116]:
df_camiones.drop(columns=['fuel_type'], inplace=True)
revisar_duplicados(df_camiones, 'truck_id')
revisar_duplicados(df_camiones_metricas, 'truck_id')
revisar_duplicados(df_camiones_mantenimiento, 'truck_id')

---------------------------------------
Los valores duplicados en la columna truck_id es de 0
---------------------------------------
Los valores duplicados en la columna truck_id es de 3220
---------------------------------------
Los valores duplicados en la columna truck_id es de 2800

<span style="color:orange">Revisamos si hay valores nulos en los archivos<span>

In [117]:
df_camiones.isna().sum()

truck_id                 0
unit_number              0
make                     0
model_year               0
vin                      0
acquisition_date         0
acquisition_mileage      0
tank_capacity_gallons    0
status                   0
home_terminal            0
dtype: int64

In [118]:
df_camiones_metricas.isna().sum()

truck_id              0
month                 0
trips_completed       0
total_miles           0
total_revenue         0
average_mpg           0
maintenance_events    0
maintenance_cost      0
downtime_hours        0
utilization_rate      0
dtype: int64

In [119]:
df_camiones_mantenimiento.isna().sum()

maintenance_id         0
truck_id               0
maintenance_date       0
maintenance_type       0
odometer_reading       0
labor_hours            0
labor_cost             0
parts_cost             0
total_cost             0
facility_location      0
downtime_hours         0
service_description    0
dtype: int64

<span style="color:orange">Y revisamos los tipos de datos<span>

In [120]:
df_camiones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   truck_id               120 non-null    object
 1   unit_number            120 non-null    int64
 2   make                   120 non-null    object
 3   model_year             120 non-null    int64
 4   vin                    120 non-null    object
 5   acquisition_date       120 non-null    object
 6   acquisition_mileage    120 non-null    int64
 7   tank_capacity_gallons  120 non-null    int64
 8   status                 120 non-null    object
 9   home_terminal          120 non-null    object
dtypes: int64(4), object(6)
memory usage: 9.5+ KB

In [121]:
df_camiones_metricas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3312 entries, 0 to 3311
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   truck_id            3312 non-null   object
 1   month               3312 non-null   object
 2   trips_completed     3312 non-null   int64
 3   total_miles         3312 non-null   int64
 4   total_revenue       3312 non-null   float64
 5   average_mpg         3312 non-null   float64
 6   maintenance_events  3312 non-null   int64
 7   maintenance_cost    3312 non-null   float64
 8   downtime_hours      3312 non-null   float64
 9   utilization_rate    3312 non-null   float64
dtypes: float64(5), int64(3), object(2)
memory usage: 258.9+ KB

In [122]:
df_camiones_mantenimiento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2920 entries, 0 to 2919
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   maintenance_id       2920 non-null   object
 1   truck_id             2920 non-null   object
 2   maintenance_date     2920 non-null   object
 3   maintenance_type     2920 non-null   object
 4   odometer_reading     2920 non-null   int64
 5   labor_hours          2920 non-null   float64
 6   labor_cost           2920 non-null   float64
 7   parts_cost           2920 non-null   float64
 8   total_cost           2920 non-null   float64
 9   facility_location    2920 non-null   object
 10  downtime_hours       2920 non-null   float64
 11  service_description  2920 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 273.9+ KB

<span style="color:orange">Estos tres archivos tienen buena pinta, los guardamos para el posterior análisis<span>

In [124]:
df_camiones.to_csv('../datos_transformados/df_camiones.csv', index=False)
df_camiones_metricas.to_csv('../datos_transformados/df_camiones_metricas.csv', index=False)
df_camiones_mantenimiento.to_csv('../datos_transformados/df_camiones_mantenimiento.csv', index=False)

## <span style="color:orange">Archivo *df_clientes.csv*<span>
<span style="color:orange">Cargamos el archivo para echar un vistazo y guardarlo para más adelante

<span style="color:orange">- *6. Qué perfil de cliente tiene la empresa. Tipos de contrato, cargas que contratan, etc* <br>
<span style="color:orange">- *7. Qué cliente es el que más abandona la empresa*

In [125]:
df_clientes = pd.read_csv('../datos_en_bruto/customers.csv', sep=',')
print(f'El número de filas que tenemos en df_clientes es {df_clientes.shape[0]}, y el número de columnas es {df_clientes.shape[1]}')

sep()
print('df_clientes:\n', df_clientes.columns)

El número de filas que tenemos en df_clientes es 200, y el número de columnas es 8
---------------------------------------
df_clientes:
 Index(['customer_id', 'customer_name', 'customer_type', 'credit_terms_days',
       'primary_freight_type', 'account_status', 'contract_start_date',
       'annual_revenue_potential'],
      dtype='object')

<span style="color:orange">Revisión de los tipos de datos, duplicados en route_id y nulos

In [126]:
df_clientes.info()
revisar_duplicados(df_clientes, 'customer_id')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               200 non-null    object
 1   customer_name             200 non-null    object
 2   customer_type             200 non-null    object
 3   credit_terms_days         200 non-null    int64
 4   primary_freight_type      200 non-null    object
 5   account_status            200 non-null    object
 6   contract_start_date       200 non-null    object
 7   annual_revenue_potential  200 non-null    int64
dtypes: int64(2), object(6)
memory usage: 12.6+ KB
---------------------------------------
Los valores duplicados en la columna customer_id es de 0

<span style="color:orange">Revisión de los tipos de datos y nulos

In [127]:
for col in df_clientes.columns:
    sep()
    print(f'Columna: *** {col} ***:')
    print(df_clientes[col].unique())

---------------------------------------
Columna: *** customer_id ***:
['CUST00001' 'CUST00002' 'CUST00003' 'CUST00004' 'CUST00005' 'CUST00006'
 'CUST00007' 'CUST00008' 'CUST00009' 'CUST00010' 'CUST00011' 'CUST00012'
 'CUST00013' 'CUST00014' 'CUST00015' 'CUST00016' 'CUST00017' 'CUST00018'
 'CUST00019' 'CUST00020' 'CUST00021' 'CUST00022' 'CUST00023' 'CUST00024'
 'CUST00025' 'CUST00026' 'CUST00027' 'CUST00028' 'CUST00029' 'CUST00030'
 'CUST00031' 'CUST00032' 'CUST00033' 'CUST00034' 'CUST00035' 'CUST00036'
 'CUST00037' 'CUST00038' 'CUST00039' 'CUST00040' 'CUST00041' 'CUST00042'
 'CUST00043' 'CUST00044' 'CUST00045' 'CUST00046' 'CUST00047' 'CUST00048'
 'CUST00049' 'CUST00050' 'CUST00051' 'CUST00052' 'CUST00053' 'CUST00054'
 'CUST00055' 'CUST00056' 'CUST00057' 'CUST00058' 'CUST00059' 'CUST00060'
 'CUST00061' 'CUST00062' 'CUST00063' 'CUST00064' 'CUST00065' 'CUST00066'
 'CUST00067' 'CUST00068' 'CUST00069' 'CUST00070' 'CUST00071' 'CUST00072'
 'CUST00073' 'CUST00074' 'CUST00075' 'CUST00076' 'CUST00077' 'CUST00078'
 'CUST00079' 'CUST00080' 'CUST00081' 'CUST00082' 'CUST00083' 'CUST00084'
 'CUST00085' 'CUST00086' 'CUST00087' 'CUST00088' 'CUST00089' 'CUST00090'
 'CUST00091' 'CUST00092' 'CUST00093' 'CUST00094' 'CUST00095' 'CUST00096'
 'CUST00097' 'CUST00098' 'CUST00099' 'CUST00100' 'CUST00101' 'CUST00102'
 'CUST00103' 'CUST00104' 'CUST00105' 'CUST00106' 'CUST00107' 'CUST00108'
 'CUST00109' 'CUST00110' 'CUST00111' 'CUST00112' 'CUST00113' 'CUST00114'
 'CUST00115' 'CUST00116' 'CUST00117' 'CUST00118' 'CUST00119' 'CUST00120'
 'CUST00121' 'CUST00122' 'CUST00123' 'CUST00124' 'CUST00125' 'CUST00126'
 'CUST00127' 'CUST00128' 'CUST00129' 'CUST00130' 'CUST00131' 'CUST00132'
 'CUST00133' 'CUST00134' 'CUST00135' 'CUST00136' 'CUST00137' 'CUST00138'
 'CUST00139' 'CUST00140' 'CUST00141' 'CUST00142' 'CUST00143' 'CUST00144'
 'CUST00145' 'CUST00146' 'CUST00147' 'CUST00148' 'CUST00149' 'CUST00150'
 'CUST00151' 'CUST00152' 'CUST00153' 'CUST00154' 'CUST00155' 'CUST00156'
 'CUST00157' 'CUST00158' 'CUST00159' 'CUST00160' 'CUST00161' 'CUST00162'
 'CUST00163' 'CUST00164' 'CUST00165' 'CUST00166' 'CUST00167' 'CUST00168'
 'CUST00169' 'CUST00170' 'CUST00171' 'CUST00172' 'CUST00173' 'CUST00174'
 'CUST00175' 'CUST00176' 'CUST00177' 'CUST00178' 'CUST00179' 'CUST00180'
 'CUST00181' 'CUST00182' 'CUST00183' 'CUST00184' 'CUST00185' 'CUST00186'
 'CUST00187' 'CUST00188' 'CUST00189' 'CUST00190' 'CUST00191' 'CUST00192'
 'CUST00193' 'CUST00194' 'CUST00195' 'CUST00196' 'CUST00197' 'CUST00198'
 'CUST00199' 'CUST00200']
---------------------------------------
Columna: *** customer_name ***:
['Metro Wholesale' 'National Retail' 'XYZ Industries' 'American Corp'
 'American Distribution' 'American Industries' 'Superior Distribution'
 'American Logistics' 'XYZ Wholesale' 'National Logistics' 'First Group'
 'ABC Distribution' 'Pacific Corp' 'Elite Foods' 'United Industries'
 'Superior Supply Chain' 'ABC Retail' 'American Supply Chain' 'First Corp'
 'Elite Industries' 'Continental Supply Chain' 'Continental Industries'
 'XYZ Distribution' 'Pacific Retail' 'ABC Supply Chain' 'Superior Foods'
 'ABC Manufacturing' 'American Manufacturing' 'Continental Wholesale'
 'XYZ Foods' 'Elite Retail' 'United Distribution' 'American Retail'
 'ABC Corp' 'First Manufacturing' 'First Logistics' 'First Wholesale'
 'Continental Corp' 'Global Manufacturing' 'Metro Corp'
 'Elite Supply Chain' 'National Corp' 'Continental Retail'
 'Premier Wholesale' 'Global Wholesale' 'Elite Group' 'Premier Group'
 'Superior Group' 'Metro Retail' 'United Retail' 'Metro Supply Chain'
 'Metro Manufacturing' 'Continental Manufacturing'
 'Continental Distribution' 'Pacific Supply Chain' 'First Industries'
 'Elite Corp' 'Metro Group' 'Pacific Logistics' 'First Distribution'
 'ABC Wholesale' 'Global Logistics' 'Metro Logistics' 'United Foods'
 'Pacific Manufacturing' 'Premier Foods' 'Continental Foods'
 'United Group' 'First Foods' 'Continental Logistics' 'National Wholesale'
 'National Supply Chain' 'ABC Foods' 'United Corp' 'Pacific Industries'
 'United Supply Chain' 'Premier Industries' 'Global Distribution'
 'Continental Group' 'Premier Manufacturing' 'Global Corp'
 'Premier Logistics' 'Superior Industries' 'Superior Corp' 'Metro Foods'
 'First Supply Chain' 'XYZ Supply Chain' 'First Retail' 'Global Group'
 'XYZ Group' 'National Distribution' 'Superior Retail' 'Premier Retail'
 'National Foods' 'ABC Group' 'Metro Distribution' 'XYZ Retail'
 'ABC Industries' 'XYZ Logistics' 'Global Foods' 'National Industries'
 'XYZ Corp' 'Pacific Foods' 'Elite Distribution' 'Pacific Group'
 'Premier Supply Chain' 'Elite Wholesale']
---------------------------------------
Columna: *** customer_type ***:
['Dedicated' 'Contract' 'Spot']
---------------------------------------
Columna: *** credit_terms_days ***:
[60 30 15 45]
---------------------------------------
Columna: *** primary_freight_type ***:
['General' 'Retail' 'Consumer Goods' 'Food/Beverage' 'Automotive'
 'Electronics']
---------------------------------------
Columna: *** account_status ***:
['Inactive' 'Active']
---------------------------------------
Columna: *** contract_start_date ***:
['2020-02-20' '2021-06-02' '2020-09-04' '2020-11-29' '2020-02-04'
 '2021-02-16' '2021-02-05' '2021-07-23' '2020-03-28' '2021-11-19'
 '2020-06-18' '2020-07-17' '2021-08-29' '2021-04-17' '2020-08-27'
 '2020-03-19' '2021-03-02' '2021-06-12' '2020-12-28' '2021-11-09'
 '2020-02-19' '2021-05-23' '2021-09-08' '2021-05-05' '2020-03-24'
 '2020-10-14' '2021-02-03' '2021-12-17' '2021-07-14' '2021-03-25'
 '2020-05-13' '2021-09-01' '2020-11-22' '2021-04-28' '2021-12-23'
 '2020-05-16' '2020-01-25' '2020-09-02' '2020-01-28' '2020-05-01'
 '2021-07-27' '2020-12-17' '2021-10-02' '2021-04-22' '2021-07-24'
 '2020-08-08' '2021-09-30' '2020-01-30' '2020-04-08' '2021-01-20'
 '2020-04-01' '2021-11-01' '2021-01-02' '2020-03-12' '2021-07-28'
 '2020-01-14' '2020-07-01' '2021-09-14' '2021-08-26' '2020-08-20'
 '2021-05-08' '2021-02-11' '2020-06-09' '2021-01-11' '2020-10-09'
 '2021-06-18' '2021-12-11' '2020-01-27' '2020-12-11' '2020-12-31'
 '2021-08-17' '2021-04-20' '2021-11-22' '2020-08-23' '2020-01-09'
 '2020-10-10' '2020-06-08' '2021-03-06' '2020-06-25' '2020-01-19'
 '2020-08-18' '2021-06-21' '2020-05-31' '2021-06-24' '2020-06-24'
 '2021-01-10' '2021-02-04' '2020-09-09' '2021-03-26' '2020-04-28'
 '2020-06-13' '2021-07-21' '2021-10-23' '2020-07-07' '2020-09-28'
 '2021-03-05' '2021-04-07' '2020-06-26' '2020-12-22' '2020-09-24'
 '2022-01-01' '2020-08-01' '2020-12-09' '2021-06-26' '2021-12-13'
 '2020-04-07' '2020-12-25' '2020-04-06' '2021-05-02' '2021-02-07'
 '2021-10-29' '2020-02-27' '2020-06-29' '2020-12-01' '2020-07-14'
 '2020-02-02' '2020-08-10' '2020-06-16' '2020-04-14' '2021-03-18'
 '2020-11-08' '2020-03-16' '2021-02-06' '2021-09-10' '2021-09-25'
 '2020-07-15' '2021-10-25' '2021-11-18' '2021-08-22' '2021-07-03'
 '2021-11-30' '2021-06-09' '2020-08-22' '2021-06-19' '2021-09-22'
 '2020-05-27' '2020-03-15' '2020-11-30' '2020-02-28' '2020-07-12'
 '2020-04-03' '2020-05-07' '2021-04-14' '2021-11-12' '2021-05-20'
 '2020-04-21' '2021-10-21' '2021-12-19' '2020-03-01' '2020-08-16'
 '2021-10-12' '2020-03-18' '2021-10-31' '2020-11-02' '2020-12-20'
 '2020-01-07' '2021-11-03' '2020-04-10' '2021-04-04' '2020-07-09'
 '2021-11-21' '2021-02-24' '2021-10-14' '2021-05-25' '2020-07-19'
 '2021-09-24' '2021-09-20' '2021-05-10' '2020-07-06' '2020-12-03'
 '2020-02-29' '2020-05-28' '2021-07-02']
---------------------------------------
Columna: *** annual_revenue_potential ***:
[ 985117 4936566 3102814 3948027 3682564  973274 1499297 1613275 4713444
 3468505 4333669 2931263 1426880 4578681 3816255 3055508 2743711 4714416
 2823396 3218209 3558986 3712034 2813302 2119327 4824000 4677044 1894559
 3246257 4715736 2231454 3119970 3895035 3853900 3431037  101641  390773
 2486409  236754 4442022 1233181 2632031  155103 2619383 1961320 1902064
 2741611  282044 2414896 4744463 4388856 4766776 4887111 4895027 1397841
  890937  416555 3961861 3083456 1409521 1261052 2322881 3179314 4983476
 2195951 2054496 2249529 2619119  870956 4885593 3453750 4873662 1923996
  747613 2823714 4147781 1550411 4195959 4933788  899971 2619881  413495
 4934218 3300640  758316  569113 2905063 3018650 3743209 3594037 1111167
 2001845  195918 3308533  554058 2656708 4498846  445461 2778621 4629258
 4838832 1354768 2841662 4314450 1952180 1385113  523790 3395738 3838099
 4925587 4333976  855670 1962989 3723339 2530876 3407816 1341618 1208882
 2919983  792438 4091758 4893591  513651 4698235 3448659 2302495  813694
 3443087 4309597 3744775 1193666 1231377 4134270 4791716 1761854 4192475
 3416174 4892669 1745000 4807415 4497709 2165659 2132686  700993 2333526
 3707652 2812973 4931991  851574 1043968 3569377 3652916 3164087 3021818
 1697943 2790548 2990084  303061 2657005 1519816 3033633 3809527 1323214
 3794875  476460 2058652 1775080 3235836 1408549  819863 1042642  557498
 2138836 1338805 2513277  215203 2979568 1033467 2659515 3875390 4052630
  290825 2883983 1853299 4613116 1877338 1809609 4683738 4489472 2269780
 4703668 4151918 1285708  254254 3259205 4990599 4519111  464753 2242923
 1528744  604239]

<span style="color:orange">Y lo guardamos

In [128]:
df_clientes.to_csv('../datos_transformados/df_clientes.csv', index=False)